### PR TITLE
Add LOC record support to OctoDNS for AXFR source, YAML, Cloudflare and PowerDNS providers

### PR DESCRIPTION
**Pull request by mtearle**
This pull request adds support for LOC records.   We were using OctoDNS to sync from YAML to Cloudflare, initial sync was failing due to a LOC record being present on Cloudflare.   This gave the excuse to implement this functionality.

### CODE REVIEW

**Comment by ross** [comment]
Interesting. Hadn't run across that type. You know if any other providers support them? 

Looks like at least PowerDNS does https://doc.powerdns.com/authoritative/appendices/types.html#loc

NS1 and Route53 don't appear to.

**Comment by mtearle** [comment]
I worked my way through the list of providers this evening.   Aside from PowerDNS, the rest will require an account to test.  Thoughts on how to proceed?


### In patch already:

octodns/source/axfr.py
octodns/provider/yaml.py
octodns/provider/cloudflare.py

### Supported:

octodns/provider/dyn.py
https://help.dyn.com/create-loc-record-api/

octodns/provider/edgedns.py
https://learn.akamai.com/en-us/webhelp/edge-dns/edge-dns-user-guide/GUID-0033207B-AC09-44DF-8022-EC62ACAEB203.html

octodns/provider/fastdns.py
https://developer.akamai.com/api/cloud_security/fast_dns_record_management/v1.html

octodns/provider/gandi.py
https://api.gandi.net/docs/livedns/#get-v5-livedns-dns-rrtypes

octodns/provider/ovh.py
https://api.ovh.com/console/#/domain/zone/{zoneName}/record#POST

octodns/provider/powerdns.py
https://doc.powerdns.com/authoritative/appendices/types.html#loc

### Not supported:


octodns/provider/azuredns.py
https://docs.microsoft.com/en-us/rest/api/dns/recordsets/createorupdate#recordtype
https://feedback.azure.com/forums/217313-networking/suggestions/38021881-support-loc-records-in-azure-public-dns-zones

octodns/provider/constellix.py
https://api-docs.constellix.com/

octodns/provider/digitalocean.py
https://developers.digitalocean.com/documentation/v2/#domain-records

octodns/provider/googlecloud.py
https://cloud.google.com/dns/docs/records#record_type

octodns/provider/mythicbeasts.py
https://www.mythic-beasts.com/support/api/dnsv2

octodns/source/tinydns.py
https://cr.yp.to/djbdns/tinydns-data.html

octodns/provider/rackspace.py
https://developer.rackspace.com/docs/cloud-dns/v1/general-api-info/supported-record-types/

octodns/provider/selectel.py
https://developers.selectel.com/docs/cloud-services/dns_api/

octodns/provider/route53.py
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html

octodns/provider/ultra.py
https://ultra-portalstatic.ultradns.com/static/docs/REST-API_User_Guide.pdf

octodns/provider/transip.py
https://api.transip.nl/rest/docs.html#domains-dns-post

octodns/provider/ns1.py
https://ns1.com/api#putcreate-a-dns-record

octodns/provider/dnsmadeeasy.py
https://api-docs.dnsmadeeasy.com/

octodns/provider/dnsimple.py
https://developer.dnsimple.com/v2/zones/
(checked via Sandbox webpage)


### Can't tell:

octodns/provider/easydns.py
https://docs.sandbox.rest.easydns.net/

**Comment by ross** [comment]
> I worked my way through the list of providers this evening. Aside from PowerDNS, the rest will require an account to test. Thoughts on how to proceed?

The list is probably good enough, I partly wanted to make sure that it's not a super esoteric thing and that there's a decent number of providers that support it (since it's still an "experimental" RFC.) Looks like that's the case. We can go ahead and ship this as-is or if there's any of the providers you want to add to it that can happen first. I'm OK with having this list of places likely to support it but not having gone through every one of them and done it. People can go through over time and add support as requested/needed.

Just let me know when you're ready for review.

**Comment by mtearle** [comment]
@ross I've implemented support for PowerDNS as I was able to test it against a local install.     For the other providers (Dyn, Edge DNS, Fast DNS, Gandi and OVH), these all require account/API access that I don't have.

In other words, it is now ready for review.

**Comment by ross** [comment]
Hi @mtearle I took a look at trying to get master merged into this PR so that it'd be up to date. The UI can't do it, but git on the command line was able to without any problems. I wasn't able to push to your branch though so I couldn't fix it. What's here generally looks good. Once it's in sync with master I can take a final pass through.

**Comment by mtearle** [comment]
Hi @ross I've caught it back up with master.  One test needed fixing.   Ready for your review now.

**Review by ross — APPROVED** [review]

**Comment by ross** [comment]
Doh. Other stuff merged and looks like the lack of permissions for me on your branch don't allow me to re-merge master. Hopefully yo can just click the button this go around and then I can merge.

**Comment by mtearle** [comment]
Hi @ross, dependencies for 2.7 are breaking CI at the moment :(

I've added read permissions for you to the ucc/octodns repo - which I think shall fix the permissions problem for the merge

**Comment by ross** [comment]
> Hi @ross, dependencies for 2.7 are breaking CI at the moment :(

I've spent the better part of an hour trying to get 2.7 happy/recreate the problems without much luck. I'm just going to give up on formal 2.7 compatibility. Will try to keep it going for ~6 months as a best effort, but after that no more. 

/cc https://github.com/octodns/octodns/pull/677

**Comment by ross** [comment]
> I've added read permissions for you to the ucc/octodns repo - which I think shall fix the permissions problem for the merge

The functionality that would let me merge master in is a checkbox, 

Screen Shot 2021-02-16 at 7 51 49 AM

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I've removed 2.7 CI to just punt on this problem so once this is updated to master one way or another it should be unblocked.

**Pull request merged**
