### PR TITLE
Ns1 fallback only support

### PR DESCRIPTION
**Pull request by ross**
This PR reworks NS1 pool/value handling to support fallback-only pools in a backwards (and forwards) compatible way (including multiple fallback chains.) 

The toughest bit was getting it so that things could cleanly come to this version (without any changes when they didn't require it) and then cleanly go back (in case the upgrade/test wasn't perminent.  

The tests that are there currently pass, but some more tests need to be added to validate the new cases (thus coverage won't yet be complete.)

/cc https://github.com/octodns/octodns/pull/698 for a PR on the same issue @viranch
/cc Fixes https://github.com/octodns/octodns/issues/696

### CODE REVIEW

**Comment by viranch** [comment]
Shouldn't `pool-only-in-fallback` from `tests/config/dynamic.tests.yaml` added in #695 test for the new test case?

**Comment by ross** [comment]
> Shouldn't `pool-only-in-fallback` from `tests/config/dynamic.tests.yaml` added in #695 test for the new test case?

Yeah that would cover one of the cases that needs testing here. The other stuff will have to do with the upgrade/downgrade cases and will be harder to hit/test. May even require some refactoring... will have to see when I get a chance to sit down and work on it, hopefully this afternoon or tomorrow.

**Comment by ross** [comment]
Testing/coverage is now complete and there's some bits hitting the new code paths during unit tests.

I've also run the case in https://github.com/octodns/octodns/issues/696 as well as some "real world" examples that I have that are close to complicated stuff I've used in the past. I've also round-tripped things from current `master`, this branch, and back to verify that things seem to work as expected/stay sane. 

/cc @pavantc @theojulienne @yeled do you all want to do any testing with this and/or review? Some of my test cases are based on things I created to act like production records so I'm fairly sure it'll work and worse case once you all upgrade it'll tell you if it's going to change a bunch of stuff... :grin:

**Review by theojulienne — APPROVED** [review]

**Comment by viranch** [comment]
can this be merged?

**Comment by ross** [comment]
> can this be merged?

Totally thought it was 😦

**Comment by viranch** [comment]
looks like this needs attention

**Comment by ross** [comment]
> looks like this needs attention

Yeah. I started to look into the conflicts locally and they weren't simple and I haven't gotten back to them yet.

**Comment by ross** [comment]
Think that got it.

**Comment by viranch** [comment]
💥 thank you!

**Pull request merged**
