### PR TITLE
Add support for checksum matching for safer plan & apply 

### PR DESCRIPTION
**Pull request by ross**
This has literally been on the TODO list since octoDNS was first created and I've finally got around to implementing it. Truth is it wasn't as important/critical as I thought it was going to be since as far as I know no one has ever run into problems w/o it, but it's straightforward enough to implement and use that I see no reason not to add it.

TL;DR you can add the following to your config file:

```yaml
manager:
  enable_checksum: true
```

To turn on the functionality. Once you do that a checksum will be computed for the generated plan any time there are changes:

```console
$ octodns-sync --config-file=config.yaml
...
2023-12-11T13:32:36  [140704644451968] INFO  Plan
********************************************************************************
* xormedia.com.
********************************************************************************
* azure (AzureProvider)
*   Create <TxtRecord TXT 3600, testing.xormedia.com., ['Hello World!']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=4
********************************************************************************


2023-12-11T13:32:36  [140704644451968] INFO  Manager sync: checksum=1f8dcbecd47f4eedf2d35cdb39d55197b2e27b24c59962d7fe6f9497839ed253
```

If you try to `--doit` to apply the changes you'll get an error about the checksum mismatch:

```
$ octodns-sync --config-file=config.yaml --doit
...
2023-12-11T13:33:17  [140704644451968] INFO  Manager sync: checksum=1f8dcbecd47f4eedf2d35cdb39d55197b2e27b24c59962d7fe6f9497839ed253
Traceback (most recent call last):
  File "/Users/ross/lib/octodnsed/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ross/octodns/octodns/octodns/cmds/sync.py", line 62, in main
    manager.sync(
  File "/Users/ross/octodns/octodns/octodns/manager.py", line 799, in sync
    raise ManagerException(
octodns.manager.ManagerException: checksum=None does not match computed=1f8dcbecd47f4eedf2d35cdb39d55197b2e27b24c59962d7fe6f9497839ed253
```

You'll get the same error if you have an actual mismatch `--checksum not-a-match`.

When you provide the correct checksum the chages are applied as normal.

```
$ octodns-sync --config-file=config.yaml --checksum 1f8dcbecd47f4eedf2d35cdb39d55197b2e27b24c59962d7fe6f9497839ed253
...
2023-12-11T13:35:09  [140704644451968] INFO  Manager sync:   1 total changes
```

/cc @octodns/review fyi and for 💭

### CODE REVIEW

**Comment by viranch** [comment]
Nice. Is there a mechanic to properly export the computed checksum for later use (either by a script or a human) apart from just a manual copy/paste? Not asking for one, just curious on the long term vision for this.

**Comment by ross** [comment]
> Nice. Is there a mechanism to properly export the computed checksum for later use (either by a script or a human) apart from just a manual copy/paste? Not asking for one, just curious on the long term vision for this.

Not currently, but that'd make sense.

**Review by viranch — APPROVED** [review]
LGTM code wise!

**Review by ross — COMMENTED** [review]
Moving forward w/this. It's safe and self contained. Labeled BETA at this point. Good news is that problems if they arise are more likely to be of the can't apply nature.

**Pull request merged**
