### PR TITLE
Add Python 3.12 to the ci test matrix and make it the current version

### PR DESCRIPTION
**Pull request by ross**
/cc https://github.com/octodns/octodns-docker/pull/97
/cc Replaces https://github.com/octodns/terraformed/pull/23

### CODE REVIEW

**Comment by viranch** [comment]
Would be nice to have the CI honor the version matrix in the PR instead of `main`.

**Comment by ross** [comment]
> Would be nice to have the CI honor the version matrix in the PR instead of `main`.

It will for octodns/octodns, the others will always be use whatever lives in main there.

**Comment by viranch** [comment]
Ah yes missed there's a CI run for 3.12 in this PR.

**Comment by ross** [comment]
I think the best flow for these PRs is to open the octodns one first, as here, make sure it's happy and then merge. Then go through and run each of the modules, either standalone or as part of PRs with needed changes (as will be the case here.) All of those PRs will be linked up.

**Pull request merged**
