### PR TITLE
Azuredns txt record too long , Skip alias entires

### PR DESCRIPTION
**Pull request by ppieprzycki**
Current azuredns provider has two issues:

**When A/CNAME ALIAS record is pointing to Azure resource, the  provider throws an error**

`File "/home/piotrek/.cache/pypoetry/virtualenvs/octodns-py3.5/lib/python3.5/site-packages/octodns/provider/azuredns.py", line 402, in _data_for_A return {'values': [ar.ipv4_address for ar in azrecord.arecords]} TypeError: 'NoneType' object is not iterable`

I've implemented a check that is verifying if the record is pointing to inside Azure Resource like CDN, Traffic Manager etc.
When ALIAS is being used the  value for arecords and cname_record is None
For this functionality I've added additional function  "_check_for_alias". 

**The second issue for me was too long TXT record** 

There is already created issue for that 
https://github.com/github/octodns/issues/361

When we try to load long txt record we will get an error from the API endpoint. 

`https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/network/azure-mgmt-dns msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/xxxxx/resourceGroups/RESGRP-xxx/providers/Microsoft.Network/dnsZones/test123.com/TXT/@?api-version=2018-05-01`

I 've tested fix on several entries. Also added this scenario to tests.  

Here is an example of how the response from the Azure DNS server looks like.

```
testtxt4.test123.com descriptive text "MS=ms123456"
testtxt4.test123.com descriptive text "v=spf1 ip4:10.10.0.0/24 ip4:10.10.1.0/24 ip4:10.10.2.0/24 ip4:10.10.3.0/24 ip4:10.10.4.0/24 ip4:10.10.5.0/24 ip4:10.10.6.0/24 ip4:10.10.7.0/24 ip4:10.10.8.0/24 ip4:10.10.9.0/24 ip4:10.10.10.0/24 ip4:10.10.11.0/24 ip4:10.10.12.0/24 ip4:10.10.13.0/24 ip4:10" ".10.14.0/24 ip4:10.10.15.0/24 ip4:10.10.16.0/24 ip4:10.10.17.0/24 ip4:10.10.18.0/24 ip4:10.10.19.0/24 ip4:10.10.20.0/24 ip4:10.10.21.0/24 ~all"
```

Here is the output from octodns-sync for multiple txt records

`test123.com.
azuredns (AzureProvider)
Create <TxtRecord TXT 3600, testtxt1.test123.com., ['singlevalue']> (config)
Create <TxtRecord TXT 3600, testtxt2.test123.com., ['multi', 'value']> (config)
Create <TxtRecord TXT 3600, testtxt3.test123.com., ['single val as list']> (config)
Create <TxtRecord TXT 3600, testtxt4.test123.com., ['MS=ms123456', 'v=spf1 ip4:10.10.0.0/24 ip4:10.10.1.0/24 ip4:10.10.2.0/24 ip4:10.10.3.0/24 ip4:10.10.4.0/24 ip4:10.10.5.0/24 ip4:10.10.6.0/24 ip4:10.10.7.0/24 ip4:10.10.8.0/24 ip4:10.10.9.0/24 ip4:10.10.10.0/24 ip4:10.10.11.0/24 ip4:10.10.12.0/24 ip4:10.10.13.0/24 ip4:10.10.14.0/24 ip4:10.10.15.0/24 ip4:10.10.16.0/24 ip4:10.10.17.0/24 ip4:10.10.18.0/24 ip4:10.10.19.0/24 ip4:10.10.20.0/24 ip4:10.10.21.0/24 ~all']> (config)
Create <TxtRecord TXT 3600, testtxt5.test123.com., ['v=spf1 ip4:10.10.0.0/24 ip4:10.10.1.0/24 ip4:10.10.2.0/24 ip4:10.10.3.0/24 ip4:10.10.4.0/24 ip4:10.10.5.0/24 ip4:10.10.6.0/24 ip4:10.10.7.0/24 ip4:10.10.8.0/24 ip4:10.10.9.0/24 ip4:10.10.10.0/24 ip4:10.10.11.0/24 ip4:10.10.12.0/24 ip4:10.10.13.0/24 ip4:10.10.14.0/24 ip4:10.10.15.0/24 ip4:10.10.16.0/24 ip4:10.10.17.0/24 ip4:10.10.18.0/24 ip4:10.10.19.0/24 ip4:10.10.20.0/24 ip4:10.10.21.0/24 ~all']> (config)
Summary: Creates=5, Updates=0, Deletes=0, Existing Records=8`

### CODE REVIEW

**Comment by ppieprzycki** [comment]
Hi 
Any way how we can move this forward. Please let me know if there is something that I should do. 
 Due to these issues, I need to use in production version from my branch. 
I'd like to use generally available package. 

Regards

**Comment by ross** [comment]
:wave: @ppieprzycki was hoping one of the devs of the Azure provider would take a look at it as I don't have an Azure setup so it's not easy for me to test. 

I'll ping the original author @h-hwang to see if he can 👁️ it. If we don't hear back soon I'll make a quick pass of looking over it and just assume it works, I guess.

**Comment by ppieprzycki** [comment]
@ross  @Arunothia @h-hwang  
Can you help me with this missing bit around the azure provider?   Delete order helps me a lot. But still, in Production, I have  long txt records and  apex entries pointed to azure resources (like traffic manager, CDN etc) 

Any Info from my side hat might be helpful to push this forward? 

Regards

**Comment by ross** [comment]
@ppieprzycki seems like the azure provider is at least somewhat abandoned at this point :-/.

As far as this PR goes I'd recommend breaking things up and doing seperat PRs for each problem rather than combining them into one since that complicates discussion and finding a path forward. E.g. I think your Alias checking is just about ready to go (with minor tweaks) and could be shipped. Less sure about the TXT length stuff as that's a more complicated area.

**Comment by Arunothia** [comment]
> @ross @Arunothia @h-hwang
> Can you help me with this missing bit around the azure provider? Delete order helps me a lot. But still, in Production, I have long txt records and apex entries pointed to azure resources (like traffic manager, CDN etc)
> 
> Any Info from my side hat might be helpful to push this forward?
> 
> Regards

I will have to pass this as I no longer work in this area. @mohitsuley Is there someone you know on Azure DNS team who can actively help maintain the Azure Provider SDK?

**Comment by rreichel3** [comment]
I'm not a member of the Azure DNS team but I was able to successfully test the `TXT` chunking code changes against my personal zone. The Azure SDK does break down at beyond `1024` chars still however this is definitely an improvement 😄 

image

## Log Output
```
2021-01-07T15:01:29  [4663508416] INFO  Manager 
********************************************************************************
* mytestdomain.com.
********************************************************************************
* azuredns (AzureProvider)
*   Update
*     <TxtRecord TXT 3600, google._domainkey.mytestdomain.com., ['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']> ->
*     <TxtRecord TXT 3600, google._domainkey.mytestdomain.com., ['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=2
********************************************************************************
```

**Comment by ross** [comment]
Going to go ahead and move forward with this one since it gets things to a better place than they currently are. I believe we'll also need to get https://github.com/octodns/octodns/issues/655 fixed to get AzureProvider back in a functional/useful state.

**Pull request merged**
