### PR TITLE
Gcore provider

### PR DESCRIPTION
**Pull request by yaroshevichd**
This PR adds new provider: G-Core.
At this moment only A, AAAA records are implemented

### CODE REVIEW

**Comment by yzguy** [comment]
Thank you for the contribution @yaroshevichd

Do you have an intention on building out this provider to support all the standard record types?

**Comment by yaroshevichd** [comment]
At least PTR records will be added a bit later. Thanks

**Comment by yaroshevichd** [comment]
@yzguy is it possible to run checks and review this PR? it's expected that PTR support will be added in separate PR. thanks in advance

**Comment by yaroshevichd** [comment]
@yzguy i've added all supported by the API records: A, AAAA, CNAME, SRV, TXT, MS, NS, PTR. Also added support of dynamics for A, AAAA, CNAME records. No more changes is expected. thanks

**Comment by yzguy** [comment]
@ross This looks good to me, full test coverage/passing. If you have no issues with it, then I think it's 👍  to merge.

**Comment by ross** [comment]
> @ross This looks good to me, full test coverage/passing. If you have no issues with it, then I think it's 👍 to merge.

👍 If you're good with it feel free to approve & merge.

**Comment by yzguy** [comment]
@yaroshevichd Approved and merged! Thanks for your contribution!

**Pull request merged**
