### PR TITLE
Replace diagram image with inline Mermaid diagram

### PR DESCRIPTION
**Pull request by bbkane**
I find the Mermaid diagram is easier to read and edit, and GitHub will render it automatically.

See comments below for what the diagram looks like

### CODE REVIEW

**Comment by bbkane** [comment]
Diagram (left to right):

```mermaid
---
title: Visual Representation of the Rules and Pools
---
flowchart LR
	query((Query)) --goelocate--> rule_0[Rule 0<br>AF-ZA<br>AS<br>OC]
	query --geolocate--> rule_1[Rule 1<br>AF<br>EU]
	query --geolocate--> rule_2["Rule 2<br>(catch all)"]
	rule_0 --to pool--> pool_apac[Pool apac<br>1.1.1.1<br>2.2.2.2]
	pool_apac --fallback--> pool_na
	rule_1 --to pool--> pool_eu["Pool eu<br>3.3.3.3 (2/5)<br>4.4.4.4 (3/5)"]
	pool_eu --fallback--> pool_na
	rule_2 --to pool---> pool_na[Pool na<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]
	pool_na --fallback--> values[values<br>3.3.3.3<br>4.4.4.4<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]

	classDef queryColor fill:#3B67A8,color:#ffffff
	classDef ruleColor fill:#D8F57A,color:#000000
	classDef poolColor fill:#F57261,color:#000000
	classDef valueColor fill:#498FF5,color:#000000

	class query queryColor
	class rule_0,rule_1,rule_2 ruleColor
	class pool_apac,pool_eu,pool_na poolColor
	class values valueColor
```

**Comment by bbkane** [comment]
Or if you'd prefer it top to bottom:

```mermaid
---
title: Visual Representation of the Rules and Pools
---
flowchart TD
	query((Query)) --goelocate--> rule_0[Rule 0<br>AF-ZA<br>AS<br>OC]
	query --geolocate--> rule_1[Rule 1<br>AF<br>EU]
	query --geolocate--> rule_2["Rule 2<br>(catch all)"]
	rule_0 --to pool--> pool_apac[Pool apac<br>1.1.1.1<br>2.2.2.2]
	pool_apac --fallback--> pool_na
	rule_1 --to pool--> pool_eu["Pool eu<br>3.3.3.3 (2/5)<br>4.4.4.4 (3/5)"]
	pool_eu --fallback--> pool_na
	rule_2 --to pool---> pool_na[Pool na<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]
	pool_na --fallback--> values[values<br>3.3.3.3<br>4.4.4.4<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]

	classDef queryColor fill:#3B67A8,color:#ffffff
	classDef ruleColor fill:#D8F57A,color:#000000
	classDef poolColor fill:#F57261,color:#000000
	classDef valueColor fill:#498FF5,color:#000000

	class query queryColor
	class rule_0,rule_1,rule_2 ruleColor
	class pool_apac,pool_eu,pool_na poolColor
	class values valueColor
```

**Review by ross — COMMENTED** [review]
2nd one is preferable to the first in terms of showing the fall back ordering, but it doesn't quite capture the concept that the rules are (currently conceptually anyway) applied in order. The "query" going into the left and rules progressing/evaluated left to right attempted to show that in the original diagram. Not sure what'd make sense with mermaid.

**Comment by bbkane** [comment]
@ross , what if we used a subgraph to call that out?

```mermaid
---
title: Visual Representation of the Rules and Pools
---
flowchart LR
  subgraph "Rules applied in order<br>defined in list"
  	query((Query)) --goelocate--> rule_0[Rule 0<br>AF-ZA<br>AS<br>OC]
	  query --geolocate--> rule_1[Rule 1<br>AF<br>EU]
	  query --geolocate--> rule_2["Rule 2<br>(catch all)"]
  end
	rule_0 --to pool--> pool_apac[Pool apac<br>1.1.1.1<br>2.2.2.2]
	pool_apac --fallback--> pool_na
	rule_1 --to pool--> pool_eu["Pool eu<br>3.3.3.3 (2/5)<br>4.4.4.4 (3/5)"]
	pool_eu --fallback--> pool_na
	rule_2 --to pool---> pool_na[Pool na<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]
	pool_na --fallback--> values[values<br>3.3.3.3<br>4.4.4.4<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]

	classDef queryColor fill:#3B67A8,color:#ffffff
	classDef ruleColor fill:#D8F57A,color:#000000
	classDef poolColor fill:#F57261,color:#000000
	classDef valueColor fill:#498FF5,color:#000000

	class query queryColor
	class rule_0,rule_1,rule_2 ruleColor
	class pool_apac,pool_eu,pool_na poolColor
	class values valueColor
```

**Comment by ross** [comment]
Played around a bit, maybe something decision tree like?

```mermaid
---
title: Visual Representation of the Rules and Pools
---
flowchart LR
  	query((Query)) --> rule_0[Rule 0<br>AF-ZA<br>AS<br>OC]
	rule_0 --no match--> rule_1[Rule 1<br>AF<br>EU]
	rule_1 --no match--> rule_2["Rule 2<br>(catch all)"]

	rule_0 --match--> pool_apac[Pool apac<br>1.1.1.1<br>2.2.2.2]
	pool_apac --fallback--> pool_na
	rule_1 --match--> pool_eu["Pool eu<br>3.3.3.3 (2/5)<br>4.4.4.4 (3/5)"]
	pool_eu --fallback--> pool_na
	rule_2 --> pool_na[Pool na<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]
	pool_na --fallback--> values[values<br>3.3.3.3<br>4.4.4.4<br>5.5.5.5<br>6.6.6.6<br>7.7.7.7]

	classDef queryColor fill:#3B67A8,color:#ffffff
	classDef ruleColor fill:#D8F57A,color:#000000
	classDef poolColor fill:#F57261,color:#000000
	classDef valueColor fill:#498FF5,color:#000000

	class query queryColor
	class rule_0,rule_1,rule_2 ruleColor
	class pool_apac,pool_eu,pool_na poolColor
	class values valueColor
```

**Comment by bbkane** [comment]
I played around with making it a diamond shape to emphasize it's a decision point, but I think the rectangles are more readable. updated PR.

**Review by ross — APPROVED** [review]
Thanks

**Pull request merged**
