### PR TITLE
DigitalOcean CAA records have a dot (.) appended arbitrarily

### PR DESCRIPTION
**Pull request by ricardbejarano**
https://github.com/octodns/octodns/pull/691#issuecomment-819228150

### CODE REVIEW

**Comment by yzguy** [comment]
Actually this isn't arbitrary. If you don't include a `.`, you will get a HTTP 422 error.

```
-> octodns-sync --config-file=./config/production.yaml yzguy.dev. --doit
2021-04-14T10:42:07  [4486348224] INFO  Manager __init__: config_file=./config/production.yaml
2021-04-14T10:42:07  [4486348224] INFO  Manager __init__:   max_workers=1
2021-04-14T10:42:07  [4486348224] INFO  Manager __init__:   include_meta=False
2021-04-14T10:42:08  [4486348224] INFO  Manager sync: eligible_zones=['yzguy.dev.'], eligible_targets=[], dry_run=False, force=False
2021-04-14T10:42:08  [4486348224] INFO  Manager sync:   zone=yzguy.dev.
2021-04-14T10:42:08  [4486348224] INFO  Manager sync:   sources=['config'] -> targets=['digitalocean']
2021-04-14T10:42:08  [4486348224] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2021-04-14T10:42:08  [4486348224] INFO  DigitalOceanProvider[digitalocean] plan: desired=yzguy.dev.
2021-04-14T10:42:08  [4486348224] WARNING DigitalOceanProvider[digitalocean] populate: skipping unsupported SOA record
2021-04-14T10:42:08  [4486348224] INFO  DigitalOceanProvider[digitalocean] populate:   found 1 records, exists=True
2021-04-14T10:42:08  [4486348224] INFO  DigitalOceanProvider[digitalocean] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=1
2021-04-14T10:42:08  [4486348224] INFO  Manager
********************************************************************************
* yzguy.dev.
********************************************************************************
* digitalocean (DigitalOceanProvider)
*   Create <CaaRecord CAA 3600, test.yzguy.dev., ['0 issue "ca.test.com"']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=1
********************************************************************************

DEBUG PARAMS: {'data': 'ca.test.com', 'flags': 0, 'name': 'test', 'tag': 'issue', 'ttl': 3600, 'type': 'CAA'}

2021-04-14T10:42:08  [4486348224] INFO  DigitalOceanProvider[digitalocean] apply: making changes
Traceback (most recent call last):
  File "/Users/yzguy/.pyenv/versions/3.8.5/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.9.11', 'console_scripts', 'octodns-sync')()
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/cmds/sync.py", line 38, in main
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/manager.py", line 424, in sync
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/provider/base.py", line 95, in apply
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/provider/digitalocean.py", line 346, in _apply
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/provider/digitalocean.py", line 317, in _apply_Create
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/provider/digitalocean.py", line 103, in record_create
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/octodns-0.9.11-py3.8.egg/octodns/provider/digitalocean.py", line 47, in _request
  File "/Users/yzguy/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.digitalocean.com/v2/domains/yzguy.dev/records
```

**Comment by ricardbejarano** [comment]
Frustrating to see someone as large as DigitalOcean bend standards to fit their implementation shortcomings for no apparent reason. 😞

**Comment by ricardbejarano** [comment]
Actually, CAA record values are a string, plain string (that's what the quotes are for), so the final dot has no meaning.

Therefore, I've modified tests to suit that spec.

**Comment by ross** [comment]
@ricardbejarano Is this ready for review?

/cc @yzguy

**Comment by ricardbejarano** [comment]
Yes!

**Review by ross — APPROVED** [review]

**Pull request merged**
