### PR TITLE
Add MetaProcessor.include_extra

### PR DESCRIPTION
**Pull request by ross**
/cc Fixes https://github.com/octodns/octodns/issues/1189
/cc @nogweii

### CODE REVIEW

**Review by ross — COMMENTED** [review]
/ci modules bump

**Comment by nogweii** [comment]
Wow, that was fast! I was hoping to ensure the continued pattern of `key=value` through the configuration, rather than completely arbitrary strings. In the documentation's example, how would one create a `foo` key with an environment variable for the value (rather than `bar`)?

**Comment by ross** [comment]
> I was hoping to ensure the continued pattern of `key=value` through the configuration

Hrm. That exact thing wouldn't be possible unless the `key=` was also in the env variable. Guess I was thinking arbitrary strings would be more flexible than forcing the `key=val`, but maybe thats more consistent with what it already does...

**Comment by nogweii** [comment]
Indeed, it's more flexible. I don't know which is more important, that flexibility or consistency with the other keys.

Appending `foo=` to any external strings is not that difficult. 😆

**Comment by ross** [comment]
I'll go ahead and switch it to a dict of keys and values. That's probalby more inline with what it already does.

**Pull request merged**
