### PR TITLE
Add support for DsRecord type

### PR DESCRIPTION
**Pull request by ross**
Added new `DsRecord` type (provider support will be added over time)

/cc Fixes https://github.com/octodns/octodns/issues/967 
/cc https://www.rfc-editor.org/rfc/rfc4034.html#section-2.1
/cc @baest @yzguy

### CODE REVIEW

**Comment by viranch** [comment]
I wonder if (in another PR) it might be possible to split this rather big `record/__init_.py` into individual files for each record type.

**Comment by baest** [comment]
Looks very good 👍 Thanks for doing this (and so quickly too)

**Comment by ross** [comment]
> I wonder if (in another PR) it might be possible to split this rather big `record/__init_.py` into individual files for each record type.

Yeah. I actually started breaking it up in a branch a while back and either got distracted or ran into a hiccup or something as I didn't finish it off. I also want to break up/clean up the tests as well.

**Comment by ross** [comment]
Since this is self contained, going to go ahead and merge it. Will poke around at breaking things up.

**Pull request merged**
