### PR TITLE
Code refactor of Azure DNS provider

### PR DESCRIPTION
**Pull request by viranch**
Just breaking down super big methods into smaller ones.

### CODE REVIEW

**Comment by ross** [comment]
Might want to watch out for https://github.com/octodns/octodns/pull/768/, there's a pretty high likelihood of conflicts.

**Comment by ross** [comment]
> Might want to watch out for #768, there's a pretty high likelihood of conflicts.

Fwiw. I've been working through the tests now and only have 50 more changes to go so it should be ready to ship :soon:

**Comment by viranch** [comment]
> watch out for #768

This PR is actually ready (the PR master race!) but don't want to hit 'ready' until CI is fixed. It will be a pain to resolve merge conflicts in either direction.

**Comment by viranch** [comment]
Actually I'll just mark this ready and re-run CI when its fixed.

I don't mind waiting to merge this until f-strings are merged and I'll resolve the conflicts after.

**Review by ross — APPROVED** [review]

**Comment by ross** [comment]
Should be easy enough to merge the other way and do a `--theirs` and replace all `.format`s, at least that path won't require thinking.

**Pull request merged**
