### PR TITLE
Skip explicit countries when converting continent to countries in NS1

### PR DESCRIPTION
**Pull request by viranch**
`NS1Provider` converts `NA` and `OC` to individual list of countries. This creates a problem when a subset of those countries are already defined in another rule pointing to a different pool. This may lead to an undefined behavior as those countries point to two different DNS responses in NS1 record. 

This PR skips over the explicitly listed countries when expanding continents to countries; and uses region notes to parse the incomplete list of continent countries back to the continent in octoDNS record.

### CODE REVIEW

**Review by ross — COMMENTED** [review]
Wish I/we'd thought to do this originally. 

To check my read (it's been a long time since I was in this bit of things) this doesn't change any of the existing behavior around continents and their mapping to a set of countries when required. 

It just adds an additional tracking of when a continent was included (via notes) and makes sure to include individual countries that are explicit on top of when they are implicitly included b/c of continent mapping?

**Comment by viranch** [comment]
Mostly correct, yes. Continent->country mapping is unaffected when none of those mapped countries are used elsewhere explicitly.

The explicit countries, when used, are skipped from the list of implicit continent mapping, rather than put on top of them. Since we can no longer map the subset back to its continent, we make use of notes to record that we want the continent not the individual countries.

**Comment by ross** [comment]
> The explicit countries, when used, are skipped from the list of implicit continent mapping, rather than put on top of them. Since we can no longer map the subset back to its continent, we make use of notes to record that we want the continent not the individual countries.

If all of the countries are still there it will get marked as a continent even though it won't be in the notes as it always previously was?

Looks like this will set the notes continent on the next update, but am I correct in my read that it won't show that as a diff?

**Comment by viranch** [comment]
The continent will stay in the notes whether or not all of it's countries are present.

**Comment by ross** [comment]
I'm mostly wondering/concerned about the impact on existing setups coming form older versions or downgrading. Cases I can think of:

* coming from old version with continent that requires country list, no explicit countries
   * will populate still convert the set of countries into the continent? 
   * will it show a diff b/c the change in notes? (ideally won't b/c that'd 😨) don't think it would have in the past and not sure it would now
   * when the record otherwise changes i assume the continent will be added to the notes (seems fine)
* coming from old version with continent that requires country list, some explicit countries
   * as i understand it this wasn't possible before this PR, if so then 👍 
* push a record with the new version, continent marked in the notes, no explicit countries, downgrade to old version
   * will everything just work the way it has in the past by turning the set into the continent? seems likely.
* push a record with the new version, continent marked in the notes, has explicit countries too, downgrade to old version
   * what happens here? my guess would be it translates the countries into continent and loses the explicit countries so shows as a diff.

**Comment by viranch** [comment]
Numbered answers to the questions:

1a. yes it will correctly map full country set to their continent in absence of the notes
1b. no we don't take notes into account when planning changes
1c. correct, the continent will be added to notes on any record update

2a. it was possible to do this but the resultant behavior in DNS responses would've been undefined (due to explicit countries being mapped to multiple pools). new version will parse such records correctly but won't show a diff for fixing the buggy setup - this is probably ok but not ideal. In order to show a diff, we'd need some transitional code in `_extra_changes` to catch such records and mark them for update, not sure if we have a standardized framework/process for handling this kind of version changes in code.

3a. correct, the older version will turn the set of countries to their continent because all countries are present

4a. yes this scenario will show a diff as it doesn't know that the subset of implicit countries actually map to their continent.  I believe this is expected if you go towards the version with the bug.

**Comment by ross** [comment]
> In order to show a diff, we'd need some transitional code in `_extra_changes` to catch such records and mark them for update, not sure if we have a standardized framework/process for handling this kind of version changes in code.

IF we wanted to `_extra_changes` would be the way to go. The fix/change should at least be included in a noteworthy changes section of the changelog. I think the use case is probably edge-case-y enough that we don't have to handle it if you don't want to beother.

Overall 👍. Will look things over once more now...

**Review by ross — APPROVED** [review]
Please ad a line to noteworthy changes in the Changelog and then feel free to merge.

**Pull request merged**
