### PR TITLE
Quick pass at implementing PlanJson

### PR DESCRIPTION
**Pull request by ross**
```yaml
manager:
  plan_outputs:
    json:
      class: octodns.provider.plan.PlanJson
      indent: '  '
```

Plan output schema is `"<target>": "<zone>": "changes"`, default is `indent=None` which would be more easily machine parsable. 

```json
{
  "out": {
    "exxampled.com.": {
      "changes": [
        {
          "new": {
            "ttl": 3600,
            "value": "1.2.3.4"
          },
          "type": "create"
        },
        {
          "new": {
            "ttl": 60,
            "values": [
              "octodns-version=1.7.0",
              "time=2024-06-04T20:59:50.929216+00:00",
              "uuid=c6613a81-2ba9-44ac-b378-9b4c59ffb04c"
            ]
          },
          "type": "create"
        },
        {
          "new": {
            "ttl": 3600,
            "value": "www.foo2."
          },
          "type": "create"
        }
      ]
    }
  }
}
```

/cc Fixes https://github.com/octodns/octodns/issues/1177 @olivergondza

### CODE REVIEW

**Comment by olivergondza** [comment]
Thanks for the prompt grooming, @ross!

My pair-review, provided with zero familiarity with octodns implementation considerations:

- I would default to indented variant—I have not seen a parser having issues with whitespace or indent. The plus is it is much easier to debug/investigate by human when things blow up.
- When presenting the plan data, it would be great to have it keyed by "modification type", so it will be easier to filter out for "Create", "Update", "Delete" operations present.
- I might be missing something, but is there a way to detect the record type?

Thanks!

**Comment by ross** [comment]
> * I would default to indented variant—I have not seen a parser having issues with whitespace or indent. The plus is it is much easier to debug/investigate by human when things blow up.

You mentioned machine readable as the main use case. It's WAY easier to grab everything on the single line/up to the newline and feed it to a json parser than to feed multiple lines. 

The more human readable format are the other plan types and there's nothing preventing configuring multiple plan outputs, one of the machine readable and the other for humans, `PlanLogger`. 

> * When presenting the plan data, it would be great to have it keyed by "modification type", so it will be easier to filter out for "Create", "Update", "Delete" operations present.

The change ordering is intention/very specific and is implemented by the ordering of change objects, https://github.com/octodns/octodns/blob/45753744a66982dd977de3bbe1ddceda07176e42/octodns/record/change.py, and Plan https://github.com/octodns/octodns/blob/main/octodns/provider/plan.py#L54-L58

A lot of providers/tooling require that things happen in that order to avoid conflicting operations, e.g. trying to create a CNAME where an A currently exists or vice versa. Everything else in octoDNS works in this ordering and I wouldn't want an built-in plan output that didn't also use it. 

> * I might be missing something, but is there a way to detect the record type?

You are correct. The record type doesn't appear to be included. Will look into that. I'm guessing the other uses of plan.data didn't need it. Should be able to add it.

**Review by ross — COMMENTED** [review]
/ci modules build

**Comment by ross** [comment]
Added `record_type`:

```js
{
  "out": {
    "exxampled.com.": {
      "changes": [
        {
          "new": {
            "ttl": 3600,
            "value": "1.2.3.4"
          },
          "record_type": "A",
          "type": "create"
        },
        {
          "new": {
            "ttl": 60,
            "values": [
              "octodns-version=1.8.0",
              "time=2024-06-10T14:46:04.848047+00:00",
              "uuid=430142f9-4b54-4055-99af-9b03c3369c24"
            ]
          },
          "record_type": "TXT",
          "type": "create"
        },
        {
          "new": {
            "ttl": 3600,
            "value": "www.foo2."
          },
          "record_type": "CNAME",
          "type": "create"
        },
        {
          "new": {
            "ttl": 3600,
            "value": "This is a TXT record with \"quotes\" in it to ensure they are handled correctly"
          },
          "record_type": "TXT",
          "type": "create"
        }
      ]
    }
  }
}
```

**Comment by olivergondza** [comment]
@ross, thanks a bunch for implementing this, and responding!

**Pull request merged**
