### PR TITLE
Python 3: use f-strings

### PR DESCRIPTION
**Pull request by ross**
* [x] Convert all the sources & provider to use f-strings, they're usually a bit shorter/cleaner and are definitely more readable in terms of what goes where in the strings.
* [x] Convert the Manager & Zone
* Not touching Constellix or Transip as they both have large active PRs that will either make the changes or they'll be made afterwards 
* Leaving tests for later as I've had enough f-string conversion for now

/cc Related https://github.com/octodns/octodns/issues/711 @viranch

### CODE REVIEW

**Comment by ross** [comment]
All the providers have been updated. Will leave this around for a week or for anyone who wonders by to :eye:, ideally provider authors would look at their own, but I don't plan to CC/assign everyone who's worked on a provider or anything. I've been careful when making the changes and a 2nd pass of being careful when `git add -p`ing them. I won't say there are no problems or anything, but it should be pretty solid.

**Comment by viranch** [comment]
Eyeballed manager.py, azuredns.py (thanks for fixing log.debugs!) and ns1.py. LGTM.

Thank you for the rather laborious work!

**Comment by ross** [comment]
See https://github.com/octodns/octodns/pull/777 for why CI is currently failing.

**Comment by ross** [comment]
> * Not touching Constellix or Transip as they both have large active PRs that will either make the changes or they'll be made afterwards
> * Leaving tests for later as I've had enough f-string conversion for now

Constellix is done, transip is temporarily removed. Tests have been f-stringed.

**Pull request merged**
