### PR TITLE
YamlProvider support for shared file, loaded into all zones

### PR DESCRIPTION
**Pull request by ross**
Add support for a "shared" yaml file in YamlProvider that is loaded for all zones using the provider. There's three main use cases I can imagine:

### Common records across all zones

This would be useful if there's a shared record(s) that should be present in all/many zones as was described in https://github.com/octodns/octodns/issues/962. 

In this case the provider config would likely look something like:

```yaml
  config:
        class: octodns.provider.yaml.YamlProvider
        directory: ./config
        shared_filename: shared.yaml
```

Records for all zones would then be placed in `./config/shared.yaml` and individual zone files with the records specific to the zones would live in `./config/something.com.yaml`.  This route may even be preferable when there are no specific zones since it would allow dynamic zone config.

### Many identical zones

All of the zones configured have exactly the same records.

```yaml
  config:
        class: octodns.provider.yaml.YamlProvider
        directory: ./config
        shared_filename: shared.yaml
        disable_zonefile: true
```

Only `./config/shared.yaml` would exist and all of the zone data would come from it. The list of zones would be explicitly configured in the main octoDNS config file.

### Combination

There's some shared records across some, but not all zones.

```yaml
  config:
        class: octodns.provider.yaml.YamlProvider
        directory: ./config
  common:
        class: octodns.provider.yaml.YamlProvider
        directory: ./config
        shared_filename: shared.yaml
        disable_zonefile: true
```

Zones with only the shared records can list `common` as their sole source. Zones with only specific records can use `config`. Finallyzones with both can list `common` and `config` as their sources. Overriding behaviors could even by achieved with the careful use of `populate_should_replace` and ordering of the sources.

P.S. the fact that this is not a 2-5 line PR shows why the refactoring was best done first :grin:

/cc https://github.com/octodns/octodns/pull/1044 which preceeds this work/change
/cc Fixes https://github.com/octodns/octodns/issues/962 @felixoi

### CODE REVIEW

**Comment by felixoi** [comment]
This currently doesn't support merging entries as mentioned in https://github.com/octodns/octodns/issues/962#issuecomment-1354585570 or?

**Comment by ross** [comment]
> This currently doesn't support merging entries as mentioned in [#962 (comment)](https://github.com/octodns/octodns/issues/962#issuecomment-1354585570), right?

No, it doesn't. I'm not really sure how that'd be implemented in a general enough fashion. Namely how people would indicate the behavior they want? Merging would make sense for TXT records, but not for other types so it seems like it'd need fine grained control. 

Even then merging wouldn't generally be safe, e.g. if there was an SPF value in both TXT records.  Keeping both of them wouldn't make sense, it'd really need to know what the TXT values were about which is definitely beyond the scope of octoDNS.  It's something that could be implemented in a custom provider if there were specific rules/logic to be applied. 

You might take a look at: https://github.com/octodns/octodns/pull/1050, it's not going to do merging, but it does offer a way to define values once and combine them into records.

**Review by ross — COMMENTED** [review]
/ci modules bump

**Comment by stavros-k** [comment]
I suppose to use this we have to wait for the next octodns release in PyPi?
Thanks!

**Comment by ross** [comment]
> I suppose to use this we have to wait for the next octodns release in PyPi?

See https://github.com/octodns/octodns#installing-a-specific-commit-sha if you're like to pick something up prior to a release.

**Comment by stavros-k** [comment]
> > I suppose to use this we have to wait for the next octodns release in PyPi?
> 
> See https://github.com/octodns/octodns#installing-a-specific-commit-sha if you're like to pick something up prior to a release.

Of course RTFM :D
Thanks, been too long I set the automation up that I forgot haha!

**Pull request merged**
